CHANNEL_CONFIGS = {
    "twitter": {
        "display_name": "X / Twitter",
        "description": "Short-form social media post paired with a Chartmetric data visual",
        "max_chars": 280,
        "tone": "Punchy, relatable, scroll-stopping. Write short lines with breathing room between them. Mix up your openers: sometimes a sharp pain point, sometimes a tension or contrast, sometimes a direct question, sometimes a bold capability statement. Keep each line short and punchy. Never make unverified claims about what artists or the industry are doing.",
        "format_rules": "Use line breaks between short punchy thoughts (2-3 lines, not a single run-on paragraph). Vary the opening style naturally. The goal is awareness of what Chartmetric makes possible, creating desire to try it. NEVER claim users are already doing something unless we have data proving it. Include 2-3 relevant hashtags at the end. No links in tweet body (added separately). Max 1 emoji if natural. STRICT: must be under 280 characters total including hashtags and line breaks. This is a hard X/Twitter API limit.",
        "audience": "Music industry professionals, artists, managers, data analysts, A&R, and music fans who follow data trends on X/Twitter",
        "example_output_format": "[Punchy opening line]\n\n[Value prop or detail]\n\n#Hashtag1 #Hashtag2 #Hashtag3",
        "enabled": True,
    },
    "email_newsletter": {
        "display_name": "Email Newsletter Block",
        "description": "Product update block for the Chartmetric newsletter",
        "max_chars": 600,
        "tone": "Benefit-first, empowering, direct. Lead with what the user can NOW do, not what was built. Second person ('you'). Warm but concise.",
        "format_rules": "Structure: Bold feature name as header line, then 2-3 sentences leading with user benefit (start with a verb or 'you' \u2014 e.g., 'Stop doing X. Now you can Y.'). Describe value before mechanics. End with CTA phrase like 'Try it here' or 'Check it out'. No HTML tags. Assume a screenshot will follow the text block. Do NOT include subject lines \u2014 this is a section within a larger newsletter, not a standalone email.",
        "audience": "Existing Chartmetric users \u2014 artists, managers, labels, publishers who use the platform daily and scan newsletters quickly",
        "example_output_format": "**[Feature Name]**\n[2-3 benefit-led sentences]. [CTA phrase].",
        "enabled": True,
    },
    "email_standalone": {
        "display_name": "Standalone Email",
        "description": "Dedicated product update or feature launch email",
        "max_chars": 1200,
        "tone": "Professional but warm. Benefit-led, second person. Slightly more expansive than the newsletter block \u2014 room to paint the picture of the problem solved.",
        "format_rules": "Structure: 'Subject: [compelling subject line]' on first line, blank line, then 2-3 short paragraphs. First paragraph: hook with the user's pain point or aspiration. Second paragraph: what's new and how it helps. Third paragraph: CTA with specific next step. Keep paragraphs to 2-3 sentences each. No HTML.",
        "audience": "Chartmetric users and trial users \u2014 may not be daily active, so context-set briefly",
        "example_output_format": "Subject: [subject]\n\n[Pain point hook paragraph]\n\n[Feature + benefit paragraph]\n\n[CTA paragraph]",
        "enabled": True,
    },
    "inapp": {
        "display_name": "In-App Announcement",
        "description": "Product announcement displayed inside the Chartmetric app",
        "max_chars": 800,
        "tone": "Clear, benefit-focused, user-empowering. Like a helpful product guide \u2014 informative but not pushy. Address the user directly.",
        "format_rules": "Structure: Title line (short, benefit-driven, with ! for energy), then 1-2 sentences introducing the feature through the lens of what the user can now do. Then 2-3 bullet points with specific capabilities or highlights (each bullet is 1-2 sentences). End with a clear navigational CTA telling the user exactly where to find it (e.g., 'Head to any Track Page, click the Playlist tab, and start discovering...'). Assume a screenshot will be shown below the text. No emoji in body text.",
        "audience": "Active Chartmetric users seeing this inside the product \u2014 they're already logged in and working",
        "example_output_format": "**[Benefit-Driven Title]!**\n\n[1-2 intro sentences]\n\n\u2022 [Capability 1]\n\u2022 [Capability 2]\n\n[Navigational CTA]",
        "enabled": True,
    },
    "linkedin": {
        "display_name": "LinkedIn Post",
        "description": "Professional thought-leadership post connecting industry trends to Chartmetric data or features",
        "max_chars": 2000,
        "tone": "Insight-led, data-backed, industry-expert voice. Open with a trend or observation that hooks music industry professionals, then weave in Chartmetric data as the proof point. Authoritative but not salesy \u2014 you're sharing knowledge, not selling a product.",
        "format_rules": "Structure: Hook opening line (industry trend, surprising data point, or provocative observation \u2014 use a single emoji like \U0001f3b5 if natural), blank line, 2-3 short paragraphs that build the narrative from trend \u2192 data \u2192 insight. Reference specific artists, numbers, or playlists when relevant. End with a CTA linking to a full article or inviting discussion. Include 3-5 hashtags on the final line. Use line breaks between paragraphs for readability. 150-300 words.",
        "audience": "Music industry executives, label heads, A&R professionals, playlist curators, and tech leaders on LinkedIn",
        "example_output_format": "[Trend hook line with optional emoji]\n\n[Paragraph expanding on the trend with specifics]\n\n[Paragraph connecting to data/Chartmetric insight]\n\n[CTA to article or discussion prompt]\n\n#hashtag1 #hashtag2 #hashtag3",
        "enabled": True,
    },
    "notion_monthly": {
        "display_name": "Notion Monthly Meeting Doc",
        "description": "Feature summary block for monthly product meeting notes",
        "max_chars": 600,
        "tone": "Concise, factual, scannable. Like a quick update in a meeting doc. Get to the point in 2-3 sentences.",
        "format_rules": "Structure: Bold feature name as a heading, then 2-3 sentences covering what changed and why it matters to users. Include a relevant link if available. End with key contributors (first names only, e.g. 'Hanby' not 'Hanby Choi'). That's it. No separate sections for Overview, User Impact, Technical Notes. Keep it tight and scannable.",
        "audience": "Chartmetric leadership and cross-functional team in a monthly product review meeting",
        "example_output_format": "### **[Feature Name]**\n\n[2-3 sentence summary of what changed and user impact]. [Link if relevant]\n\nKey Contributors: [first names only]",
        "enabled": True,
    },
    "article_hmc": {
        "display_name": "HMC Blog Article",
        "description": "SEO-optimized long-form article for How Music Charts (hmc.chartmetric.com)",
        "max_chars": 10000,
        "tone": "Strategic, empowering, direct-address ('you'). Write like a savvy music industry mentor coaching an ambitious indie artist or professional. Conversational authority \u2014 confident and opinionated but backed by data and real examples. Not dry or academic. Not promotional \u2014 Chartmetric features are framed as tools the reader can use, not products being sold.",
        "format_rules": "Structure: SEO-friendly H1 title with primary keyword (e.g., 'Promoting Your Music as an Indie Artist on Chartmetric'). Intro paragraph: Hook with the reader's challenge or aspiration, cite a compelling stat to establish stakes, preview what the article covers. Target long-tail SEO phrases naturally in the intro (e.g., 'how do I get my song on Spotify playlists'). Then 3-5 H2 sections, each covering one Chartmetric feature or strategy. Each H2 section should include: feature name + where to find it, what it does framed as user benefit, step-by-step guidance, a 'Why this matters' block with data/context, and a 'Pro tip' with insider advice. Use specific numbers and real-world examples (artist names, percentage growth, stream counts). End with a short empowering closing section. Include a 'meta_description' field (155 chars max) for SEO. Write in second person ('you'). 1000-2000 words.",
        "audience": "Independent artists, emerging managers, music students, and early-career professionals searching Google for music promotion strategies and data tools",
        "example_output_format": "meta_description: [155-char SEO description]\n\n# [SEO Title with Primary Keyword]\n\n[Hook intro paragraph with stats + SEO phrases]\n\n## [Feature/Strategy 1 Name]\n[Feature description + user benefit]\n[How to access/use it]\n**Why this matters:** [data-backed context]\n**Pro tip:** [insider advice]\n\n## [Feature/Strategy 2 Name]\n...\n\n## [Empowering Closing Header]\n[1-2 sentence empowering close]",
        "enabled": True,
    },
}
